name: React Native.ts CI/CD
 on:
   push:
     branches:
       - development
     pull_request:
       branches:
         - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependences
        run: npm install

      - name: Run Testes
        run: npm run test

      - name: Build Next.js
        run: npm run build

  deploy:
    name: Deploy to vercel
    needs: build
    runs-on: ubuntu-lastest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/setup-node@v3
      - name: Install dependences
        run: npm install

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
      
     
